services:
  postgres:
    image: postgres:17
    container_name: bank-rest-api-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bank
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: